import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { extname, join, relative } from "node:path";
import ignore from "ignore";
import { config } from "../config.js";

const SKIP_DIRS = new Set([
	".git",
	"node_modules",
	"vendor",
	"dist",
	"build",
	"__pycache__",
	".next",
	".svelte-kit",
	"coverage",
	".cache",
	".turbo",
	".output",
	"target",
	"out",
	".idea",
	".vscode",
	".pytest_cache",
	".mypy_cache",
	".tox",
	"venv",
	".venv",
	"env",
	// Frameworks
	".nuxt",
	".expo",
	".angular",
	".parcel-cache",
	".docusaurus",
	".nx",
	// Build/cache
	"_site",
	"_build",
	"CMakeFiles",
	"obj",
	// Package managers
	".pnpm-store",
	".bundle",
	"Pods",
	// VCS
	".svn",
	".hg",
	// Language tooling
	".gradle",
	".mvn",
	".dart_tool",
	".pub-cache",
	".zig-cache",
	".ruff_cache",
	// Infra
	".terraform",
	".serverless",
	// IDE
	".vs",
	".eclipse",
	".settings",
	// Temp/logs
	"tmp",
	"temp",
	"logs",
	"log",
	// Cache/coverage
	".coverage",
	// Platform
	"DerivedData",
	// Vendored
	"third_party",
	"3rdparty",
]);

const SKIP_EXTENSIONS = new Set([
	".lock",
	".min.js",
	".min.css",
	".map",
	".wasm",
	".png",
	".jpg",
	".jpeg",
	".gif",
	".ico",
	".svg",
	".webp",
	".mp3",
	".mp4",
	".wav",
	".ogg",
	".pdf",
	".zip",
	".tar",
	".gz",
	".bz2",
	".7z",
	".rar",
	".exe",
	".dll",
	".so",
	".dylib",
	".o",
	".a",
	".pyc",
	".pyo",
	".class",
	".jar",
	".war",
	".ttf",
	".woff",
	".woff2",
	".eot",
	".otf",
	// Temp/backup
	".tsbuildinfo",
	".swp",
	".swo",
	".bak",
	".tmp",
	".orig",
	".log",
	// Database
	".db",
	".sqlite",
	".sqlite3",
	// Archives
	".tgz",
	".xz",
	".zst",
	// Images
	".bmp",
	".tif",
	".tiff",
	".avif",
	".heic",
	// Design
	".psd",
	".ai",
	".sketch",
	".fig",
	// Video
	".mov",
	".mkv",
	".webm",
	// Audio
	".flac",
	".aac",
	// Native/compiled
	".node",
	".bin",
	".dat",
	// Python packages
	".whl",
	".egg",
	// Data formats
	".parquet",
	".arrow",
	".h5",
	".hdf5",
	".pkl",
	".pickle",
	// ML models
	".onnx",
	".pt",
	".pth",
	".safetensors",
	// Installers
	".dmg",
	".iso",
	".msi",
	".deb",
	".rpm",
]);

const SKIP_FILES = new Set([
	"package-lock.json",
	"yarn.lock",
	"pnpm-lock.yaml",
	"bun.lockb",
	"Cargo.lock",
	"poetry.lock",
	"Gemfile.lock",
	"composer.lock",
	".DS_Store",
	"Thumbs.db",
	".env",
	".env.local",
	".env.development",
	".env.production",
	".env.staging",
	".env.test",
	"credentials.json",
	"service-account.json",
	".npmrc",
	".pypirc",
	".netrc",
	"id_rsa",
	"id_ed25519",
	".htpasswd",
	// Additional lock files
	"uv.lock",
	"go.sum",
	"Pipfile.lock",
	"flake.lock",
	".terraform.lock.hcl",
	// OS artifacts
	"desktop.ini",
]);

const GENERATED_FILE_MARKERS = [
	"CODE GENERATED",
	"DO NOT EDIT",
	"GENERATED FILE",
	"THIS FILE IS AUTOGENERATED",
	"THIS FILE WAS GENERATED",
	"AUTO-GENERATED",
	"AUTO GENERATED",
	"AUTOMATICALLY GENERATED",
	"GENERATED BY",
	"@GENERATED",
	"DO NOT MODIFY",
];

const MINIFIED_AVG_LINE_THRESHOLD = 500;

export function isGeneratedFile(content: string): boolean {
	const header = content.slice(0, 1000).toUpperCase();
	return GENERATED_FILE_MARKERS.some((marker) => header.includes(marker));
}

export function isMinifiedFile(content: string): boolean {
	const lineCount = content.split("\n").length;
	if (lineCount === 0) return false;
	return content.length / lineCount > MINIFIED_AVG_LINE_THRESHOLD;
}

function createIgnoreFilter(rootPath: string) {
	const ig = ignore();

	try {
		const gitignoreContent = readFileSync(join(rootPath, ".gitignore"), "utf-8");
		ig.add(gitignoreContent);
	} catch {
		// .gitignore doesn't exist — that's fine
	}

	return ig;
}

const LANGUAGE_MAP: Record<string, string> = {
	".ts": "typescript",
	".tsx": "tsx",
	".js": "javascript",
	".jsx": "javascript",
	".mjs": "javascript",
	".cjs": "javascript",
	".py": "python",
	".go": "go",
	".rs": "rust",
	".java": "java",
	".c": "c",
	".h": "c",
	".cpp": "cpp",
	".cc": "cpp",
	".cxx": "cpp",
	".hpp": "cpp",
	".hh": "cpp",
	".cs": "csharp",
	".rb": "ruby",
	".php": "php",
	".swift": "swift",
	".kt": "kotlin",
	".scala": "scala",
	".sh": "bash",
	".bash": "bash",
	".zsh": "bash",
	".sql": "sql",
	".html": "html",
	".css": "css",
	".scss": "scss",
	".less": "less",
	".json": "json",
	".yaml": "yaml",
	".yml": "yaml",
	".toml": "toml",
	".xml": "xml",
	".md": "markdown",
	".mdx": "markdown",
	".svelte": "svelte",
	".vue": "vue",
};

export interface ScannedFile {
	filePath: string;
	language: string | null;
	content: string;
	contentHash: string;
	sizeBytes: number;
	lineCount: number;
}

export function scanRepository(clonePath: string): ScannedFile[] {
	const files: ScannedFile[] = [];
	const ig = createIgnoreFilter(clonePath);
	walkDirectory(clonePath, clonePath, files, ig);

	files.sort((a, b) => {
		const aIsPriority = isPriorityPath(a.filePath);
		const bIsPriority = isPriorityPath(b.filePath);
		if (aIsPriority && !bIsPriority) return -1;
		if (!aIsPriority && bIsPriority) return 1;
		return a.filePath.localeCompare(b.filePath);
	});

	if (files.length > config.maxFilesPerRepo) {
		return files.slice(0, config.maxFilesPerRepo);
	}

	return files;
}

function isPriorityPath(filePath: string): boolean {
	const parts = filePath.split("/");
	const first = parts[0];
	return ["src", "lib", "app", "pkg", "cmd", "internal"].includes(first);
}

function walkDirectory(
	rootPath: string,
	currentPath: string,
	files: ScannedFile[],
	ig: ReturnType<typeof ignore>,
): void {
	let entries: string[];
	try {
		entries = readdirSync(currentPath);
	} catch {
		return;
	}

	for (const entry of entries) {
		const fullPath = join(currentPath, entry);
		const relativePath = relative(rootPath, fullPath);

		let stat;
		try {
			stat = statSync(fullPath);
		} catch {
			continue;
		}

		if (stat.isDirectory()) {
			if (SKIP_DIRS.has(entry)) continue;
			if (ig.ignores(`${relativePath}/`)) continue;
			walkDirectory(rootPath, fullPath, files, ig);
			continue;
		}

		if (!stat.isFile()) continue;

		if (SKIP_FILES.has(entry)) continue;

		const ext = extname(entry).toLowerCase();
		if (SKIP_EXTENSIONS.has(ext)) continue;

		if (ig.ignores(relativePath)) continue;

		if (stat.size > config.maxFileSize) continue;
		if (stat.size === 0) continue;

		let content: string;
		try {
			const buffer = readFileSync(fullPath);
			// Check for binary content (null bytes in first 8KB)
			const sample = buffer.subarray(0, 8192);
			if (sample.includes(0)) continue;
			content = buffer.toString("utf-8");
		} catch {
			continue;
		}

		if (isGeneratedFile(content)) continue;
		if (isMinifiedFile(content)) continue;

		const language = LANGUAGE_MAP[ext] || null;

		files.push({
			filePath: relativePath,
			language,
			content,
			contentHash: createHash("sha256").update(content).digest("hex"),
			sizeBytes: stat.size,
			lineCount: content.split("\n").length,
		});
	}
}

export function buildFileTree(files: ScannedFile[]): string {
	const tree: Record<string, unknown> = {};

	for (const file of files) {
		const parts = file.filePath.split("/");
		let current = tree;
		for (let i = 0; i < parts.length - 1; i++) {
			if (!current[parts[i]]) {
				current[parts[i]] = {};
			}
			current = current[parts[i]] as Record<string, unknown>;
		}
		current[parts[parts.length - 1]] = null;
	}

	const lines: string[] = [];
	renderTree(tree, "", lines);
	return lines.join("\n");
}

function renderTree(node: Record<string, unknown>, indent: string, lines: string[]): void {
	const entries = Object.entries(node).sort(([a, av], [b, bv]) => {
		const aIsDir = av !== null;
		const bIsDir = bv !== null;
		if (aIsDir && !bIsDir) return -1;
		if (!aIsDir && bIsDir) return 1;
		return a.localeCompare(b);
	});

	for (const [name, value] of entries) {
		if (value === null) {
			lines.push(`${indent}${name}`);
		} else {
			lines.push(`${indent}${name}/`);
			renderTree(value as Record<string, unknown>, `${indent}  `, lines);
		}
	}
}
