import { describe, expect, test } from "bun:test";
import { isGeneratedFile, isMinifiedFile } from "$lib/server/pipeline/scanner.js";

describe("isGeneratedFile", () => {
	test("detects CODE GENERATED marker", () => {
		expect(isGeneratedFile("// CODE GENERATED by some tool\nconst x = 1;")).toBe(true);
	});

	test("detects DO NOT EDIT marker", () => {
		expect(isGeneratedFile("/* DO NOT EDIT */\nmodule.exports = {};")).toBe(true);
	});

	test("detects @generated marker", () => {
		expect(isGeneratedFile("// @generated\nexport const schema = {};")).toBe(true);
	});

	test("detects AUTO-GENERATED marker", () => {
		expect(isGeneratedFile("# AUTO-GENERATED FILE\ndef hello(): pass")).toBe(true);
	});

	test("detection is case-insensitive", () => {
		expect(isGeneratedFile("// code generated by tool")).toBe(true);
		expect(isGeneratedFile("// Code Generated By Tool")).toBe(true);
	});

	test("returns false for normal code", () => {
		expect(isGeneratedFile("const x = 1;\nfunction hello() {}")).toBe(false);
	});

	test("ignores markers after first 1000 chars", () => {
		const padding = "x".repeat(1001);
		expect(isGeneratedFile(`${padding}CODE GENERATED`)).toBe(false);
	});

	test("detects marker at exactly the 1000-char boundary", () => {
		const padding = "x".repeat(980);
		expect(isGeneratedFile(`${padding}CODE GENERATED`)).toBe(true);
	});
});

describe("isMinifiedFile", () => {
	test("returns false for normal code", () => {
		const lines = Array.from({ length: 10 }, (_, i) => `const x${i} = ${i};`);
		expect(isMinifiedFile(lines.join("\n"))).toBe(false);
	});

	test("returns true when average line length exceeds threshold", () => {
		const longLine = "a".repeat(600);
		expect(isMinifiedFile(longLine)).toBe(true);
	});

	test("returns false for multi-line file with normal lines", () => {
		const lines = Array.from({ length: 100 }, () => "const x = 1;");
		expect(isMinifiedFile(lines.join("\n"))).toBe(false);
	});

	test("returns true for single very long line (minified JS)", () => {
		const minified = `var a=1,b=2,c=3;${"d();".repeat(200)}`;
		expect(isMinifiedFile(minified)).toBe(true);
	});

	test("returns false for empty string", () => {
		expect(isMinifiedFile("")).toBe(false);
	});
});
